### ISSUE TITLE
Create assets - logo - fonts - favicon - buttons

### ISSUE THREAD

**Issue by nam1962** [nam1962/returnsworth#14]

**Comment by Noreea** [comment]
https://apidock.com/rails/ActionView/Helpers/AssetTagHelper/favicon_link_tag

**Comment by Noreea** [comment]
Logo : colis

**Comment by nam1962** [comment]
https://looka.com/editor/132284306

**Comment by nam1962** [comment]
![Image](https://github.com/nam1962/returnsworth/assets/7419235/171accac-3093-4307-8d4c-71e3f20f508a)



![Image](https://github.com/nam1962/returnsworth/assets/7419235/e309abc6-749f-4662-8bf9-b8284484acb5)




![Image](https://github.com/nam1962/returnsworth/assets/7419235/1803829c-667b-4115-bad1-d8cea1a41cff)

**Comment by nam1962** [comment]
![Image](https://github.com/nam1962/returnsworth/assets/7419235/4e81ccff-9c46-41be-8cab-bbdffe05ddb2)
![Image](https://github.com/nam1962/returnsworth/assets/7419235/92de236a-ac14-477b-9e93-33b7436f5762)

**Comment by nam1962** [comment]
Outil d'aide à création : https://www.visme.co/

**Comment by nam1962** [comment]
![Image](https://github.com/nam1962/returnsworth/assets/7419235/1fd58f0c-8673-490f-9c23-6bfd9f276474)
![Image](https://github.com/nam1962/returnsworth/assets/7419235/8e691962-5b90-4f46-9bcf-a59e0739c2a3)
![Image](https://github.com/nam1962/returnsworth/assets/7419235/655f45bd-0ce3-4524-8c7a-2c01a51ae22d)
![Image](https://github.com/nam1962/returnsworth/assets/7419235/703965d9-0462-436a-85b9-1b6a23f72673)

**Comment by nam1962** [comment]
ajout du fichier _buttons.scss
dans stylesheets/components:
.btn-primary {
background-color: #f1b60d!important;
border-radius: 15px!important;

}

.btn-primary:hover {
outline: 2px solid #f1b60d;
}

.btn-dark:hover {
outline: 2px solid #37342c;
}

**Comment by cmsavary** [comment]
avec canva, hyper facile de créer logo "animé" : https://www.canva.com/design/DAFmk-4RBnA/1m_Z6Irkui0g--qy_OGgsg/edit
gifs cartons émotions : 
https://i.gifer.com/Gt3W.gif
https://i.gifer.com/YhSD.gif
https://i.gifer.com/OVN.gif
https://gfycat.com/badwhicharabianoryx
https://gfycat.com/tepidfarflungaegeancat
https://gfycat.com/lankyunitedeeve

**Comment by cmsavary** [comment]
carton heureux : https://tenor.com/fr/view/fizza-smile-emoji-cute-box-gif-15601779

**Comment by cmsavary** [comment]
![Image](https://github.com/nam1962/returnsworth/assets/121505176/54f8f194-03f6-49af-8314-3702e82b8c9d)

**Comment by cmsavary** [comment]
![Image](https://github.com/nam1962/returnsworth/assets/121505176/64782357-3638-4b82-a41f-0ebae56fb845)

**Comment by cmsavary** [comment]
![Image](https://github.com/nam1962/returnsworth/assets/121505176/e5cd0a4a-d866-4463-973d-701325b76a32)

**Comment by cmsavary** [comment]
![Image](https://github.com/nam1962/returnsworth/assets/121505176/1834dbb5-5211-456d-b806-d155805fb81d)

**Comment by cmsavary** [comment]
https://kulturegeek.fr/news-281226/vivatech-robot-miroka-entre-fantaisie-partenaire-professionnel

**Comment by cmsavary** [comment]
Parcours logisticien façon jeu vidéo (ultra simplifié) avec récompenses (divertir l'user, participer à son bien-être et le stimuler, le motiver) : à chaque fois qu'il finit, les cartons s'accumulent comme dans jeux : C'est ce qu'on appelle le catcher (ou “l'attrapeur”). Il se contrôle à l'aide de la souris, des touches fléchées ou simplement en touchant l'écran. Les participants déplacent le catcher horizontalement pour attraper les objets qui tombent. Chaque bon objet attrapé ajoute des points au score du participant.
= bonne expérience user/ bonne pratique salariale, rh, bien-être des salariés
=démo wagon, effet whaouh ou au moins fun ? 
=> façon tetris ?
On fait une démo tradi (pour bien montrer le parcours et après on enchaine vite une 10 aine de cartons pour montrer le "jeu"
Ce n'est qu'une idée :)))

**Comment by cmsavary** [comment]
Développer jeu Tetris en JS et HTML : https://www.youtube.com/watch?v=RFxWTBQWqGc

**Comment by cmsavary** [comment]
fonts.scss : lien url google fonts + css fonts

**Comment by cmsavary** [comment]
doc Bootstrap en français :  https://www.pierre-giraud.com/bootstrap-apprendre-cours/couleur-fond-opacite/
