### ISSUE TITLE
FIGMA

### ISSUE THREAD

**Issue by nam1962** [nam1962/returnsworth#29]

**Comment by Noreea** [comment]
https://www.figma.com/file/VtT6pqLMFaFHPhncSR88II/Untitled?type=design&node-id=4-20&t=JTtLpmAtTS6rWaJ9-0

**Comment by nam1962** [comment]
Coolors

60-30-10

**Comment by cmsavary** [comment]
emojis :   https://fr.piliapp.com/emoji/list/

**Comment by cmsavary** [comment]
https://fr.freepik.com/photos-vecteurs-libre/fond-carton
