### ISSUE TITLE
Define mood - Ambiance

### ISSUE THREAD

**Issue by nam1962** [nam1962/returnsworth#37]

**Comment by nam1962** [comment]
Pros, travail routinier, faciliter la tâche et mettre un côté agréable, émotionnel avec logo cute, changements de couleur en fonction de l’avancement…

**Comment by nam1962** [comment]
Lecture facile en fonction luminosité entrepôt: couleurs, polices, intensité, contrastes, idem couleurs

**Comment by nam1962** [comment]
Couleurs parfaitement significatives (sans ambiguïté)

**Comment by cmsavary** [comment]
https://www.altrum.com/fr/ressources/articles/influence-couleurs-milieu-de-travail/
https://www.smow.fr/themes/lumiere/eclairage-au-bureau.html
https://www.codeur.com/blog/comment-choisir-contraste-couleurs/
https://www.arquen.fr/blog/ui-design-comment-choisir-les-bonnes-couleurs/

Les employés plus âgés ou malvoyants ont besoin d'un nombre de lux plus élevé, c'est-à-dire entre 750 et 1.500 lux, tandis que les employés plus jeunes et en bonne santé visuelle n’ont besoin que de 500 lux
la température de couleur - généralement indiquée en Kelvin - a également une influence sur le bien-être.
Physiologiquement, plus la couleur de la lumière est élevée donc froide et bleuté, plus notre rythme biologique est actif. 
éclairage blanc neutre d'env. 4000 Kelvin
Les couleurs chaudes sont très stimulantes. Le rouge est LA couleur de la productivité!
Les prises de décisions sont également facilitées dans des environnements jaunes ou oranges
Le rose active les émotions positives, apaise et diminue le stress

**Comment by cmsavary** [comment]
palettes:
number 1 : https://coolors.co/palette/0d3b66-faf0ca-f4d35e
https://coolors.co/palette/eca400-eaf8bf-006992-27476e-001d4a
https://coolors.co/palette/ff6b35-f7c59f-efefd0-004e89-1a659e
https://coolors.co/palette/ff6700-ebebeb-c0c0c0-3a6ea5-004e98
https://coolors.co/palette/000000-14213d-fca311-e5e5e5-ffffff
https://coolors.co/palette/003049-d62828-f77f00-fcbf49-eae2b7
