### ISSUE TITLE
home page background logisticiens en action vidéo

### ISSUE THREAD

**Issue by nam1962** [nam1962/returnsworth#61]

**Comment by nam1962** [comment]
https://gpte.ai/tag/video/

**Comment by nam1962** [comment]
https://www.pexels.com/search/videos/store/

**Comment by cmsavary** [comment]
home.html.erb
<div class="row">
      <%= video_tag "videoblocks-steadycam-shot-of-big-warehouse-with-many-goods-for-building-or-repair-shopping-mall-or-stock-with-stuff-for-decoration_r8zf9u7zwz__f0dcea737d629327c0ac627221b9660e__P360.mp4", :size => "320x240", :controls => true %>
    </div>

assets.erb
Rails.application.config.assets.paths << Rails.root.join("app", "assets", "videos")

manifest.js
//= link videoblocks-steadycam-shot-of-big-warehouse-with-many-goods-for-building-or-repair-shopping-mall-or-stock-with-stuff-for-decoration_r8zf9u7zwz__f0dcea737d629327c0ac627221b9660e__P360.mp4
