### ISSUE TITLE
How to do a PWA ?

### ISSUE THREAD

**Issue by nam1962** [nam1962/returnsworth#8]
https://kitt.lewagon.com/knowledge/tutorials/from_web_app_to_pwa

**Comment by nam1962** [comment]
https://www.pwabuilder.com/imagegenerator

https://www.npmjs.com/package/pwa-asset-generator

**Comment by Noreea** [comment]
Instruction d'installation :
https://kitt.lewagon.com/knowledge/tutorials/from_web_app_to_pwa

Lien vers notre app :
https://cb05-89-3-26-77.ngrok-free.app/

**Comment by Noreea** [comment]
Instruction ngrok :
https://dashboard.ngrok.com/get-started/setup
et
https://gist.github.com/wosephjeber/aa174fb851dfe87e644e
